source "https://supermarket.chef.io"

# metadata

cookbook "system"
cookbook "locale"
cookbook "apt"
cookbook "vim"
cookbook "apache2", "~> 3.0"
cookbook "mysql", "~> 7.0"
cookbook "memcached", "~> 3.0"
cookbook "rvm", "~> 0.9.4"
cookbook "mailcatcher", "~> 0.1.0"
cookbook "nodejs", "~> 2.0"
cookbook "graft", path: "graft"
